<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Girish-PC" name="FirefoxTest" tests="3" failures="1" timestamp="14 Dec 2014 13:48:58 GMT" time="20.888" errors="0">
  <testcase name="@BeforeMethod preCondition" time="0.0" classname="com.Actitime.testcases.AT_Login_Invalid">
    <failure type="org.openqa.selenium.remote.SessionNotFoundException" message="Session ID is null. Using WebDriver after calling quit()?
Build info: version: &amp;apos;2.43.1&amp;apos;, revision: &amp;apos;5163bce&amp;apos;, time: &amp;apos;2014-09-10 16:27:33&amp;apos;
System info: host: &amp;apos;Girish-PC&amp;apos;, ip: &amp;apos;192.168.43.121&amp;apos;, os.name: &amp;apos;Windows 7&amp;apos;, os.arch: &amp;apos;x86&amp;apos;, os.version: &amp;apos;6.1&amp;apos;, java.version: &amp;apos;1.7.0_45&amp;apos;
Driver info: driver.version: RemoteWebDriver">
      <![CDATA[org.openqa.selenium.remote.SessionNotFoundException: Session ID is null. Using WebDriver after calling quit()?
Build info: version: '2.43.1', revision: '5163bce', time: '2014-09-10 16:27:33'
System info: host: 'Girish-PC', ip: '192.168.43.121', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.7.0_45'
Driver info: driver.version: RemoteWebDriver
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.firefox.internal.NewProfileExtensionConnection.execute(NewProfileExtensionConnection.java:165)
	at org.openqa.selenium.firefox.FirefoxDriver$LazyCommandExecutor.execute(FirefoxDriver.java:362)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:572)
	at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:304)
	at com.Actitime.libraries.SuperTestNG.preCondition(SuperTestNG.java:49)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeMethod preCondition -->
  <testcase name="@AfterMethod postCondition" time="0.0" classname="com.Actitime.testcases.AT_Login_Invalid">
    <skipped/>
  </testcase> <!-- @AfterMethod postCondition -->
  <testcase name="testParameterWithXML" time="3.274" classname="com.practice.Guru99CrossBrowserScript"/>
  <testcase name="testAT_Login_Valid" time="3.613" classname="com.Actitime.testcases.AT_Login_Valid">
    <failure type="java.lang.AssertionError" message="expected [actiTIME - Enter Time-Track] but found [actiTIME - Login]">
      <![CDATA[java.lang.AssertionError: expected [actiTIME - Enter Time-Track] but found [actiTIME - Login]
	at com.Actitime.libraries.ProjectSpecific.verifyTitle(ProjectSpecific.java:66)
	at com.Actitime.testcases.AT_Login_Valid.testAT_Login_Valid(AT_Login_Valid.java:24)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- testAT_Login_Valid -->
  <testcase name="testAT_Login_Invalid" time="0.006" classname="com.Actitime.testcases.AT_Login_Invalid">
    <skipped/>
  </testcase> <!-- testAT_Login_Invalid -->
</testsuite> <!-- FirefoxTest -->
